import React, { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { ScreenHeader } from '../../../shared';
import { resetPasswordWithRecoveryCode } from '../services/accountRepository';

export function ForgotPasswordScreen({ onBack }: { onBack: () => void }) {
  const [username, setUsername] = useState(''); const [code, setCode] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(false);
  const submit = async () => { if (password !== confirm) { setError(true); setMessage('Hai mật khẩu chưa trùng nhau.'); return; } try { await resetPasswordWithRecoveryCode(username, code, password); setError(false); setMessage('Đã đặt lại mật khẩu. Bạn có thể quay lại đăng nhập.'); } catch (cause) { setError(true); setMessage(cause instanceof Error ? cause.message : 'Không thể đặt lại mật khẩu.'); } };
  return <View style={styles.page}><ScreenHeader title="Quên mật khẩu" onBack={onBack} /><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.note}>Khôi phục cục bộ bằng mã đã khai báo khi tạo tài khoản. Tài khoản demo: admin dùng 111111, user dùng 222222.</Text><Field label="Tên đăng nhập" value={username} onChangeText={setUsername} /><Field label="Mã khôi phục" value={code} onChangeText={setCode} secureTextEntry /><Field label="Mật khẩu mới" value={password} onChangeText={setPassword} secureTextEntry /><Field label="Nhập lại mật khẩu" value={confirm} onChangeText={setConfirm} secureTextEntry />{message ? <Text style={error ? styles.error : styles.success}>{message}</Text> : null}<Pressable style={styles.button} onPress={submit}><Text style={styles.buttonText}>Đặt lại mật khẩu</Text></Pressable></ScrollView></View>;
}
function Field(props: React.ComponentProps<typeof TextInput> & { label: string }) { const { label, ...rest } = props; return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput {...rest} autoCapitalize="none" style={styles.input} /></View>; }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: '#F4F7FB' }, content: { padding: 22 }, note: { backgroundColor: '#EDF5FF', borderRadius: 9, color: '#24598F', lineHeight: 19, marginBottom: 16, padding: 12 }, field: { marginBottom: 13 }, label: { color: '#344057', fontWeight: '700', marginBottom: 6 }, input: { backgroundColor: '#FFF', borderColor: '#CBD4E1', borderRadius: 9, borderWidth: 1, color: '#172033', paddingHorizontal: 12, paddingVertical: 11 }, error: { color: '#B42318', marginBottom: 12 }, success: { color: '#18713D', marginBottom: 12 }, button: { alignItems: 'center', backgroundColor: '#B01432', borderRadius: 9, paddingVertical: 13 }, buttonText: { color: '#FFF', fontWeight: '800' } });
