# Enable explicitly with: --spring.profiles.active=remote
spring.datasource.url=${BOOKING_DB_URL:jdbc:h2:ssl://tyvcf-171-234-224-53.run.pinggy-free.link:42091/booking;IFEXISTS=TRUE}
spring.datasource.username=${BOOKING_DB_USERNAME:sa}
spring.datasource.password=${BOOKING_DB_PASSWORD:}
