spring.config.import=optional:file:./application-local.properties
server.port=8080
server.address=0.0.0.0
spring.jackson.default-property-inclusion=non_null
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.datasource.url=jdbc:h2:ssl://tyvcf-171-234-224-53.run.pinggy-free.link:42091/booking;IFEXISTS=TRUE
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
user.timezone=Asia/Ho_Chi_Minh
