import React, { useCallback, useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { ScreenHeader } from '../../../shared';
import { createTemporaryPin, getPinDisplayStatus, getRoomPinPermissions } from '../../access_control';
import { getRooms, type Room } from '../../room_management';
import { BookingInfo } from '../components/BookingInfo';
import type { Booking } from '../model/booking';
import { cancelBooking, getBookingsForUser, setPickupDelegate, toLocalDateTime } from '../services/bookingRepository';

const PIN_STATUS_LABEL = { PENDING: 'Chưa đến thời gian hiệu lực', ACTIVE: 'Đang có hiệu lực', EXPIRED: 'Đã hết hạn', REVOKED: 'Đã thu hồi' };
type DelegateDraft = { fullName: string; studentId: string };

export function MyBookingsScreen({ username, onBack }: { username: string; onBack: () => void }) {
  const [bookings, setBookings] = useState<Booking[]>([]); const [rooms, setRooms] = useState<Room[]>([]); const [revealedPinId, setRevealedPinId] = useState<string | null>(null); const [message, setMessage] = useState(''); const [delegates, setDelegates] = useState<Record<string, DelegateDraft>>({});
  const [permittedRoomIds, setPermittedRoomIds] = useState<string[]>([]);
  const load = useCallback(async () => { const [items, roomItems, permissionItems] = await Promise.all([getBookingsForUser(username), getRooms(), getRoomPinPermissions()]); setBookings(items); setRooms(roomItems); setPermittedRoomIds(permissionItems.filter(item => item.username === username && item.active).map(item => item.roomId)); }, [username]);
  useEffect(() => { load(); }, [load]);
  const active = bookings.filter(item => ['PENDING', 'APPROVED'].includes(item.status) && toLocalDateTime(item.date, item.endTime) > new Date());
  const action = async (operation: () => Promise<unknown>, success: string) => { try { await operation(); setMessage(success); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Không thể thực hiện thao tác.'); } };
  const updateDelegate = (id: string, field: keyof DelegateDraft, value: string) => setDelegates(current => ({ ...current, [id]: { ...(current[id] ?? { fullName: '', studentId: '' }), [field]: value } }));
  return <View style={styles.page}><ScreenHeader title="Đặt phòng của tôi" onBack={onBack} /><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    {message ? <Text style={styles.message}>{message}</Text> : null}{active.length === 0 ? <Text style={styles.empty}>Không có yêu cầu đang chờ hoặc sắp sử dụng.</Text> : active.map(booking => {
      const room = rooms.find(item => item.id === booking.roomId); const pin = booking.temporaryPin?.revokedAt ? undefined : booking.temporaryPin; const reveal = revealedPinId === booking.id; const pinStatus = getPinDisplayStatus(booking); const draft = delegates[booking.id] ?? { fullName: '', studentId: '' };
      const canCreatePin = permittedRoomIds.includes(booking.roomId);
      return <View key={booking.id} style={styles.card}><BookingInfo booking={booking} />
        {pin ? <View style={styles.pinBox}><Text style={styles.pinLabel}>Mã mở cửa · {pinStatus ? PIN_STATUS_LABEL[pinStatus] : ''}</Text><Text style={styles.pinCode}>{reveal ? pin.code : '••••••'}</Text><Text style={styles.pinTime}>Hiệu lực: {new Date(pin.validFrom).toLocaleString('vi-VN')} – {new Date(pin.validUntil).toLocaleString('vi-VN')}</Text><Pressable onPress={() => setRevealedPinId(reveal ? null : booking.id)}><Text style={styles.link}>{reveal ? 'Ẩn mã' : 'Xem mã'}</Text></Pressable></View> : null}
        {!pin && booking.status === 'APPROVED' && room?.lockType === 'PIN_CODE' && canCreatePin ? <View style={styles.permission}><Text style={styles.permissionText}>Bạn có quyền tự tạo mã cho riêng phòng {room.name}.</Text><Pressable style={styles.purpleButton} onPress={() => action(() => createTemporaryPin(booking.id, username, 'user'), 'Đã tạo mật khẩu tạm thời.')}><Text style={styles.whiteText}>Tạo mật khẩu tạm thời</Text></Pressable></View> : null}
        {!pin && booking.status === 'APPROVED' && room?.lockType === 'PIN_CODE' && !canCreatePin ? <Text style={styles.waiting}>Quyền tự tạo mã của phòng này đã bị thu hồi. Liên hệ cán bộ quản lý để được hỗ trợ.</Text> : null}
        {booking.status === 'APPROVED' && room?.lockType === 'PHYSICAL_KEY' ? <View style={styles.delegateBox}><Text style={styles.boxTitle}>Ủy quyền người nhận khóa/thẻ hộ</Text><TextInput placeholder="Họ tên người nhận hộ" placeholderTextColor="#7D8795" style={styles.input} value={draft.fullName} onChangeText={value => updateDelegate(booking.id, 'fullName', value)} /><TextInput placeholder="Mã sinh viên / cán bộ" placeholderTextColor="#7D8795" style={styles.input} value={draft.studentId} onChangeText={value => updateDelegate(booking.id, 'studentId', value)} /><Pressable style={styles.outlineButton} onPress={() => action(() => setPickupDelegate(booking.id, username, draft.fullName, draft.studentId), 'Đã lưu người nhận khóa hộ.')}><Text style={styles.outlineText}>Lưu ủy quyền</Text></Pressable></View> : null}
        <Pressable style={styles.cancelButton} onPress={() => action(() => cancelBooking(booking.id, username), 'Đã hủy đặt phòng và thu hồi quyền truy cập liên quan.')}><Text style={styles.cancelText}>{booking.status === 'PENDING' ? 'Rút yêu cầu' : 'Hủy đặt phòng'}</Text></Pressable>
      </View>;
    })}
  </ScrollView></View>;
}
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: '#F4F7FB' }, content: { padding: 18, paddingBottom: 40 }, message: { backgroundColor: '#EDF5FF', borderRadius: 9, color: '#24598F', marginBottom: 12, padding: 11 }, empty: { color: '#657084', marginTop: 40, textAlign: 'center' }, card: { backgroundColor: '#FFF', borderColor: '#E1E6EE', borderRadius: 13, borderWidth: 1, marginBottom: 13, padding: 16 }, pinBox: { backgroundColor: '#F4F0FF', borderRadius: 9, marginTop: 13, padding: 12 }, pinLabel: { color: '#5C4778', fontSize: 12, fontWeight: '800' }, pinCode: { color: '#3B235F', fontSize: 24, fontWeight: '900', letterSpacing: 4, marginTop: 6 }, pinTime: { color: '#62547B', fontSize: 11, marginTop: 6 }, link: { color: '#6A42A1', fontWeight: '800', marginTop: 8 }, permission: { backgroundColor: '#F4F0FF', borderRadius: 9, marginTop: 12, padding: 11 }, permissionText: { color: '#5C4778', marginBottom: 8 }, purpleButton: { alignItems: 'center', backgroundColor: '#5A3788', borderRadius: 8, paddingVertical: 10 }, whiteText: { color: '#FFF', fontWeight: '800' }, waiting: { backgroundColor: '#FFF7E7', borderRadius: 8, color: '#765014', marginTop: 12, padding: 10 }, delegateBox: { backgroundColor: '#F7F9FC', borderRadius: 9, marginTop: 12, padding: 11 }, boxTitle: { color: '#344057', fontWeight: '800', marginBottom: 8 }, input: { backgroundColor: '#FFF', borderColor: '#CBD4E1', borderRadius: 8, borderWidth: 1, color: '#172033', marginBottom: 8, paddingHorizontal: 10, paddingVertical: 9 }, outlineButton: { alignItems: 'center', borderColor: '#386E9F', borderRadius: 8, borderWidth: 1, paddingVertical: 9 }, outlineText: { color: '#315A86', fontWeight: '800' }, cancelButton: { alignSelf: 'flex-start', marginTop: 13, paddingVertical: 5 }, cancelText: { color: '#B01432', fontSize: 13, fontWeight: '800' } });
